---
title: "SOL, CHS, and BHRC PFAS Other Analyses"
author: "Zhenjiang Li"
date: today
toc: true
toc_expand: 2
format:
  html:
    code-fold: true
    html-math-method: katex
    fontsize: 16pt
    grid:
      sidebar-width: 0px
      body-width: 1500px
      margin-width: 500px
      gutter-width: 1.5rem
embed-resources: true
editor: visual
editor_options:
  chunk_output_type: console
---

## Environment Setup {.hidden}

```{=html}
<style type="text/css">
caption, .table-caption {
  text-align: left;
}
</style>
```

```{r setup}
#| echo: false

options(scipen=999)

library(fs)
library(here)
i_am("1_scripts/!analytic_workflow_pfas_other.qmd")

source(fs::path("1_scripts", "!libraries.R"))
source(fs::path("1_scripts", "!directories.R"))
source(fs::path("1_scripts", "!functions.R"))

options(knitr.table.format = "html")
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

```{r}
#| label: shorten-long-path
#| include: false

create_shortcut <- function(path, short_cut, drive)
{
  return(
    sub(gsub("\\)", "\\\\)", gsub("\\(", "\\\\(", short_cut)), paste0(drive, ":"), path))
}

if(nchar(dir_data) > 80)
{
  system("subst x: /D")
  short_cut <- dir_home |> dirname()
  system(paste0("subst x: \"", short_cut, "\""))

  dir_objects_names <- ls(pattern = "^dir_")

  dir_list <- mget(dir_objects_names)

  dir_list_shortened <- lapply(
    dir_list,
    function(y) create_shortcut(y, short_cut, "x")
  )
  list2env(dir_list_shortened, envir = .GlobalEnv)
}

rm(dir_objects_names, short_cut, dir_list, dir_list_shortened)
```

# Parameters

```{r}
SOLAR_pfas_names <- c("pfos_log2", "pfoa_log2", "pfna_log2", "pfda_log2", "pfhxs_log2", "pfhps_log2")
CHS_pfas_names <- c("ma_pfos_log2", "ma_pfoa_log2", "ma_pfna_log2", "ma_pfda_log2", "ma_pfhxs_log2", "ma_pfhps_log2")
BHRC_pfas_names <- c("PFOS_log2", "PFOA_log2", "PFNA_log2", "PFDA_log2", "PFHxS_log2", "PFHpS_log2")
PFAS_abbrev_names <- c("PFOS", "PFOA", "PFNA", "PFDA", "PFHxS", "PFHpS")

SOLAR_covars <- c("age", "sex", "bmiz", "tanner", "wave", "edu_house2")
CHS_covars <- c("ma_age", "ma_sex", "ma_hisp", "ma_race_eth", "ma_parental_edu", "ma_bmi")
BHRC_raw_covars <- c("AGE_AT_VISIT", "BMI1", "GENDER", "YEARS_EDU", "ADA2010_DM")
BHRC_covars <- c("AGE_AT_VISIT", "BMI1", "GENDER", "edu_3level", "ADA2010_DM")
```

# Data Preparation

## Bridged proteomics

```{r}
proteomics_l <- readRDS(fs::path(
  dir_data,
  "ShARP_BHRC_Shared",
  "ShARP_BHRC_Data_Shared",
  "OLINK_proteomics_bridged_BHRC_SOLAR_CHS.rds"
  ))

cohort_names <- c("SOLAR", "CHS", "BHRC")
proteomics_metadata_cols <- c("LABID", "study", "Batch")

overlap_proteins <- proteomics_l[cohort_names] %>%
  purrr::map(~ setdiff(names(.x), proteomics_metadata_cols)) %>%
  purrr::reduce(intersect)

proteomics_l <- proteomics_l[c(cohort_names, "protein_annotation")]

proteomics_l[cohort_names] <- proteomics_l[cohort_names] %>%
  purrr::map(~ .x %>% dplyr::select(tidyselect::any_of(proteomics_metadata_cols), tidyselect::all_of(overlap_proteins)))

proteomics_l$protein_annotation <- proteomics_l$protein_annotation[cohort_names] %>%
  purrr::map(~ .x %>% dplyr::filter(meta_id %in% overlap_proteins))

SOL_prote <- proteomics_l$SOLAR %>%
  dplyr::mutate(id = gsub("-", "_", tolower(LABID))) %>%
  dplyr::select(id, tidyselect::all_of(overlap_proteins))

CHS_prote <- proteomics_l$CHS %>%
  dplyr::rename(SampleID = LABID) %>%
  dplyr::select(SampleID, tidyselect::all_of(overlap_proteins))

BHRC_prote <- proteomics_l$BHRC %>%
  dplyr::select(LABID, tidyselect::all_of(overlap_proteins))

proteomics_property <- proteomics_l$protein_annotation$SOLAR %>%
  dplyr::transmute(
    OlinkID = meta_id,
    UniProt = meta_Uniprot,
    Assay = meta_id,
    Protein = meta_Assay,
    Panel = NA_character_
  )

cat("Overlapping proteins across SOLAR, CHS, and BHRC:", length(overlap_proteins), "\n")
names(proteomics_l)
```

## SOLAR

```{r solar-data-prep}
load(fs::path(
  dir_data,
  "ShARP_SOLAR_Shared",
  "ShARP_SOLAR_Data_Shared",
  "Solar_Analysis_20251003.Rda"
))
SOLAR <- analysis_df
rm(analysis_df)

SOLAR_visit1 <- SOLAR %>%
  dplyr::group_by(id) %>%
  dplyr::filter(visit == min(visit)) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(
    edu_house2 = dplyr::recode(
      edu_house,
      "Missing" = "Missing",
      "Did not graduate high school" = "< High School",
      "High school graduate" = "High School Grad",
      "Partial college (at least one year) or specialized training" = "> High School",
      "Completed college/university" = "> High School",
      "Graduate professional training (graduate degree)" = "> High School"
    )
  ) %>%
  dplyr::select(
    id,
    tidyselect::all_of(SOLAR_pfas_names),
    tidyselect::all_of(SOLAR_covars)
  )

colSums(is.na(SOLAR_visit1))

SOLAR_working_df <- SOL_prote %>%
  dplyr::left_join(SOLAR_visit1, by = "id")

colSums(is.na(SOLAR_working_df))
dim(SOLAR_working_df)
```

## CHS

```{r chs-data-prep}
CHS <- readRDS(fs::path(
  dir_data,
  "ShARP_CHS_Shared",
  "ShARP_CHS_Data_Shared",
  "CHS MetaAir MetaChem Cleaned Redcap and Exposures Outcome Data long V4.rds"))

id_link <- read_xlsx(
  fs::path(
  here::here() |> dirname() |> dirname() |> dirname() |> dirname() |> dirname(),
  "Chatzi Projects and Analyses", "Env Chem SOL-CHS",
  "Lab Analysis and sample shipments", "Metachem_sample_inventory_master_040522.xlsx"),
  sheet = "Plasma"
)

id_link_simp <- id_link %>%
  dplyr::mutate(
    SampleID = `Plasma Aliquot ID`,
    id = `Sample Name`
  ) %>%
  dplyr::mutate(
    id = as.character(id)
  ) %>%
  dplyr::select(SampleID, id)

CHS_prote <- CHS_prote |>
  dplyr::left_join(
    id_link_simp,
    by = c("SampleID")
  ) %>%
  dplyr::select(id, tidyselect::everything(), -SampleID)
duplicated(CHS_prote$id) |> sum() # all unique IDs

CHS_baseline <- CHS %>%
  dplyr::filter(study == "MetaAir") %>%
  dplyr::select(
    id,
    tidyselect::all_of(CHS_pfas_names),
    tidyselect::all_of(CHS_covars)
  ) %>%
  dplyr::mutate(
    ma_hisp = as.factor(ma_hisp),
    ma_race_eth = as.factor(ma_race_eth),
    ma_parental_edu = dplyr::na_if(ma_parental_edu, -1),
    ma_parental_edu = as.factor(ma_parental_edu),
    ma_sex = as.factor(ma_sex)
  )

colSums(is.na(CHS_baseline))

CHS_analysis_df <- CHS_baseline %>%
  dplyr::filter(complete.cases(.))

CHS_working_df <- dplyr::left_join(
  CHS_prote,
  CHS_analysis_df,
  by = "id"
)

colSums(is.na(CHS_working_df))
dim(CHS_working_df)
```

## BHRC

```{r}
BHRC <- readRDS(
  fs::path(
    dir_data,
    "ShARP_BHRC_Shared",
    "ShARP_BHRC_Data_Shared",
    "CCHC_usc250_long_12172025.rds"
  )
) |>
  dplyr::filter(visit %in% c(1,2))
  # dplyr::filter(visit %in% c(1))

BHRC_pfas <- readRDS(
  fs::path(
    dir_data,
    "ShARP_BHRC_Shared",
    "ShARP_BHRC_Data_Shared",
    "PFAS_CCHC.rds"
  )
)

BHRC_analysis_df <- BHRC %>%
  dplyr::filter(visit == 1) %>%
  dplyr::select(
    RRID,
    LABID,
    visit,
    tidyselect::all_of(BHRC_raw_covars)
  ) %>%
  dplyr::left_join(
    BHRC_pfas %>%
      dplyr::select(RRID, tidyselect::all_of(BHRC_pfas_names)),
    by = "RRID"
  ) %>%
  dplyr::mutate(
    GENDER = as.factor(GENDER),
    YEARS_EDU_code = code_from_years_edu(YEARS_EDU),
    edu_3level = bhrc_edu_3level(YEARS_EDU_code),
    ADA2010_DM = as.factor(ADA2010_DM)
  ) %>%
  dplyr::filter(complete.cases(dplyr::select(., tidyselect::all_of(c(BHRC_pfas_names, BHRC_covars))))) %>%
  dplyr::arrange(LABID, visit) %>%
  dplyr::distinct(LABID, .keep_all = TRUE)

BHRC_working_df <- BHRC_prote %>%
  dplyr::left_join(BHRC_analysis_df, by = "LABID")

colSums(is.na(BHRC_working_df))
dim(BHRC_working_df)
```

# Descriptive Analyses

## Table 1

```{r}
table1(
  as.formula(paste("~", paste(SOLAR_covars, collapse = " + "))),
  data = SOLAR_working_df
)

table1(
  as.formula(paste("~", paste(CHS_covars, collapse = " + "))),
  data = CHS_working_df
)

table1(
  as.formula(paste("~", paste(BHRC_covars, collapse = " + "))),
  data = BHRC_working_df
)
```


